# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'colaborator/', verbose_name=b'Foto')),
                ('social_network', models.URLField(max_length=255, verbose_name=b'Rede Social')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
            },
        ),
    ]
